### ISSUE TITLE
Doesn't work anymore with latest bancontact app

### ISSUE THREAD

**Issue by AttilaGal** [Razer2015/BancontactRootBypasser#2]
Hi,

The bypasser used to work perfectly, up until a recent bancontact update.
My setup:
device: OnePlus One
Android: v5.1.1 (CyanogenMod)
bancontact app: v2.3.5.894

I even tried a complete clean install of the OS, but to no avail.

**Comment by Razer2015** [comment]
@AttilaGal 

Hi,

I think I finally found the new root detection methods. If you could test the new version and give me a feedback on whether it works or not?

Download here: https://github.com/Razer2015/BancontactRootBypasser/releases/tag/v1.1
Or Xposed repo: http://repo.xposed.info/module/fi.razerman.bancontactrootbypasser

**Comment by AttilaGal** [comment]
@Razer2015 your update seems to have done the trick, thanks for fixing it so quickly!

**Comment by Razer2015** [comment]
Glad to hear it works 👍 

_(BTW, couldn't bypass the USB debugging toast message but it should still work with USB debugging on)_
