### ISSUE TITLE
Version 2.5

### ISSUE THREAD

**Issue by slothje** [Razer2015/BancontactRootBypasser#4]
Is there support coming for version 2.5?

**Comment by Razer2015** [comment]
@slothje 

I've updated it and it now has a new way of blocking so please report back on how it works:
Download Github: https://github.com/Razer2015/BancontactRootBypasser/releases/tag/v1.3
Download Xposed Repo: http://repo.xposed.info/module/fi.razerman.bancontactrootbypasser

**Comment by slothje** [comment]
That was fast! It opens again on my phone, thanks!
